-keep class rikka.shizuku.** { *; }
-keep class moe.shizuku.** { *; }
-keep class com.eightball.pool.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
